apiVersion: batch/v1
kind: CronJob
metadata:
  name: study-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Cronjob Schedule is Running # 시간 Logging
          restartPolicy: OnFailure
