apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
#  namespace: ns1
  namespace: ns2
  labels:
    app: nginx
spec:
  # strategy:
  #   type: "Recreate"  ## default = RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: nginx # Label 중에 중에 app: nginx 의 K-V Pair 을 가진 Pod 를 Select
  template:
    metadata:
      labels:
        app: nginx
        # metadata Label 에 위에서 찾고자 하는 app: nginx Pair 을 넣음으로써, 해당 Pod 가 위 Deployment Resource 에 의해 배포될 것을 의미
    spec:
      containers:
      - name: nginx
        # changed 1.22.1 to 1.25.4
        image: nginx:1.25.4
        ports:
        - containerPort: 80

---
# NodePort 예시
apiVersion: v1
kind: Service
metadata:
 name: nginx-np-svc
# namespace: ns1
 namespace: ns2
spec:
 type: NodePort
 selector:
   app: nginx
 ports:
     # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
   - port: 80
     targetPort: 80
     # Optional field
     # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
#     nodePort: 30007
---
# ClusterIP 예시
apiVersion: v1
kind: Service
metadata:
  name: nginx-cl-svcs
#  namespace: ns1
  namespace: ns2
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
#---
## LoadBalancer 예시
#apiVersion: v1
#kind: Service
#metadata:
# name: nginx-lb-svc
#spec:
# selector:
#   app: nginx
# type: LoadBalancer
# ports:
# - name: http
#   port: 80
#   targetPort: 80
