apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev # 뒤에 붙는 태그 개념
resources:
- ../../base # base kustomization 위치
labels:
- includeSelectors: true # default: false
  pairs:
    env: development
patches:
- path: deployment-patch.yaml
