apiVersion: v1
kind: Pod
metadata:
  name: my-ubuntu
spec:
  containers:
  - name: my-ubuntu
    image: changi/ubuntu:24.04
    imagePullPolicy: IfNotPresent
    command: ["echo"] # ENTRYPOINT
    args: ["Hello, Kubernetes! Its Perfectly Overwritten"] # CMD
    # 기존 Dockerfile 의 ENTRYPOINT 와 CMD 를 덮고 실행된다
